import type { Metadata } from "next";
import AuthHeader from "./_components/AuthHeader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="border-b bg-white/70 backdrop-blur">
          <div className="max-w-6xl mx-auto px-4 py-2 flex items-center justify-between">
            <span className="font-semibold text-gray-800">IdeaSeek</span>
            <AuthHeader />
          </div>
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
