export type StrategyTrack = {
  id: string;
  title: string;
  title_zh: string;
  description?: string;
  reddit: {
    subreddits: string[];
    keywordsText: string;
  };
};

const CORE_KEYWORDS = [
  'How do you... / What tool do you use for...',
  'Is there a tool that... / I wish there was...',
  'X software is terrible / alternative to X',
  "I'm spending hours doing...",
  'We keep messing up...',
];

export const STRATEGY_TRACKS: StrategyTrack[] = [
  {
    id: 'personal_finance',
    title: 'Personal Finance',
    title_zh: 'Personal Finance',
    description: 'Budgeting, investing, and money management pain points.',
    reddit: {
      subreddits: [
        'personalfinance',
        'financialindependence',
        'frugal',
        'povertyfinance',
        'investing',
        'stocks',
        'bogleheads',
        'creditcards',
        'debtfree',
        'budgeting',
        'financialplanning',
        'retirement',
        'tax',
        'sidehustle',
        'money',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'budgeting app / expense tracking',
        'credit score monitoring',
        'debt payoff plan',
        'investment tracker',
        'tax filing software',
        'retirement planning tool',
      ].join('\n'),
    },
  },
  {
    id: 'fitness',
    title: 'Fitness',
    title_zh: 'Fitness',
    description: 'Training, nutrition, and habit-building workflows.',
    reddit: {
      subreddits: [
        'fitness',
        'loseit',
        'bodyweightfitness',
        'gainit',
        'running',
        'weightlifting',
        'powerlifting',
        'crossfit',
        'xxfitness',
        'keto',
        'nutrition',
        'intermittentfasting',
        'yoga',
        'bodybuilding',
        'cycling',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'workout plan generator',
        'macro tracking / calorie logging',
        'meal prep planner',
        'habit tracker for training',
        'injury recovery routine',
        'sleep tracking for fitness',
      ].join('\n'),
    },
  },
  {
    id: 'pets',
    title: 'Pets',
    title_zh: 'Pets',
    description: 'Pet care, training, and health management.',
    reddit: {
      subreddits: [
        'pets',
        'dogs',
        'cats',
        'puppy101',
        'dogtraining',
        'catcare',
        'petadvice',
        'veterinary',
        'dogfood',
        'catfood',
        'animaltraining',
        'rabbits',
        'parrots',
        'ferrets',
        'pethealth',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'vet appointment reminders',
        'pet insurance comparison',
        'behavior issues / training plan',
        'feeding schedule tracker',
        'grooming checklist',
        'lost pet recovery tool',
      ].join('\n'),
    },
  },
  {
    id: 'learning',
    title: 'Learning & Productivity',
    title_zh: 'Learning & Productivity',
    description: 'Study systems, focus, and knowledge management.',
    reddit: {
      subreddits: [
        'productivity',
        'getdisciplined',
        'studying',
        'learnprogramming',
        'languagelearning',
        'notetaking',
        'college',
        'gradschool',
        'selfimprovement',
        'learning',
        'digitalnomad',
        'notion',
        'obsidianmd',
        'anki',
        'reading',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'study planner / schedule',
        'spaced repetition workflow',
        'note-taking system',
        'focus timer / deep work',
        'course tracking dashboard',
        'reading list manager',
      ].join('\n'),
    },
  },
  {
    id: 'sales',
    title: 'Sales & CRM',
    title_zh: 'Sales & CRM',
    description: 'Pipeline, prospecting, and CRM operations.',
    reddit: {
      subreddits: [
        'sales',
        'salesops',
        'salesforce',
        'crm',
        'leadgeneration',
        'b2b',
        'coldemail',
        'marketing',
        'entrepreneur',
        'startups',
        'smallbusiness',
        'saas',
        'customersuccess',
        'growthhacking',
        'business',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'lead list building',
        'pipeline tracking',
        'deal follow-up reminders',
        'crm cleanup / data hygiene',
        'sales call notes',
        'outreach sequencing',
      ].join('\n'),
    },
  },
  {
    id: 'indie_saas',
    title: 'Indie SaaS',
    title_zh: 'Indie SaaS',
    description: 'Founder workflows, product discovery, and growth.',
    reddit: {
      subreddits: [
        'saas',
        'startups',
        'entrepreneur',
        'indiehackers',
        'sideproject',
        'smallbusiness',
        'webdev',
        'programming',
        'productivity',
        'productmanagement',
        'marketing',
        'growthhacking',
        'nocode',
        'buildinpublic',
        'analytics',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'customer discovery / interviews',
        'onboarding checklist',
        'pricing experiments',
        'churn analysis',
        'support ticket workflow',
        'feature request tracking',
      ].join('\n'),
    },
  },
  {
    id: 'small_business_ops',
    title: 'Small Business Ops',
    title_zh: 'Small Business Ops',
    description: 'Operations, bookkeeping, and day-to-day execution.',
    reddit: {
      subreddits: [
        'smallbusiness',
        'entrepreneur',
        'operations',
        'bookkeeping',
        'accounting',
        'ecommerce',
        'shopify',
        'etsy',
        'amazonfba',
        'marketing',
        'localbusiness',
        'logistics',
        'customerexperience',
        'projectmanagement',
        'retail',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'inventory tracking',
        'vendor management',
        'order fulfillment workflow',
        'cash flow tracker',
        'staff scheduling',
        'process checklist',
      ].join('\n'),
    },
  },
  {
    id: 'marketing',
    title: 'Marketing',
    title_zh: 'Marketing',
    description: 'Demand generation, content, and growth execution.',
    reddit: {
      subreddits: [
        'marketing',
        'digital_marketing',
        'content_marketing',
        'socialmedia',
        'facebookads',
        'ppc',
        'seo',
        'emailmarketing',
        'copywriting',
        'branding',
        'growthhacking',
        'ecommerce',
        'analytics',
        'startups',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'content calendar planning',
        'utm tracking / attribution',
        'ad creative testing',
        'email campaign workflow',
        'landing page optimization',
        'social posting scheduler',
      ].join('\n'),
    },
  },
  {
    id: 'hr_recruiting',
    title: 'HR & Recruiting',
    title_zh: 'HR & Recruiting',
    description: 'Hiring pipelines, onboarding, and people operations.',
    reddit: {
      subreddits: [
        'recruiting',
        'humanresources',
        'hr',
        'jobs',
        'resumes',
        'interviews',
        'careerguidance',
        'hiring',
        'talentacquisition',
        'onboarding',
        'remotework',
        'careers',
        'work',
        'management',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'candidate sourcing workflow',
        'resume screening',
        'interview scheduling',
        'offer approval checklist',
        'onboarding playbook',
        'candidate relationship management',
      ].join('\n'),
    },
  },
  {
    id: 'parenting',
    title: 'Parenting',
    title_zh: 'Parenting',
    description: 'Family routines, child care, and school coordination.',
    reddit: {
      subreddits: [
        'parenting',
        'mommit',
        'daddit',
        'toddlers',
        'beyondthebump',
        'babybumps',
        'newparents',
        'breastfeeding',
        'kids',
        'family',
        'childdevelopment',
        'homeschooling',
        'workingmoms',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'sleep schedule tracker',
        'meal planning for kids',
        'behavior charts',
        'school communication organizer',
        'family calendar syncing',
        'parenting tips digest',
      ].join('\n'),
    },
  },
  {
    id: 'travel',
    title: 'Travel',
    title_zh: 'Travel',
    description: 'Trip planning, budgeting, and coordination.',
    reddit: {
      subreddits: [
        'travel',
        'solotravel',
        'backpacking',
        'digitalnomad',
        'travelhacks',
        'flights',
        'awardtravel',
        'camping',
        'roadtrip',
        'onebag',
        'japantravel',
        'europetravel',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'trip itinerary builder',
        'budget travel planner',
        'visa / entry checklist',
        'packing list generator',
        'flight deal alerts',
        'group trip coordination',
      ].join('\n'),
    },
  },
  {
    id: 'gaming',
    title: 'Gaming',
    title_zh: 'Gaming',
    description: 'Players, communities, and session coordination.',
    reddit: {
      subreddits: [
        'gaming',
        'pcgaming',
        'nintendo',
        'nintendoswitch',
        'xbox',
        'playstation',
        'gamedev',
        'indiegaming',
        'games',
        'gamecollecting',
        'minecraft',
        'esports',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'matchmaking / team finder',
        'performance tracking stats',
        'gaming setup optimizer',
        'game backlog tracker',
        'coop session scheduler',
        'patch notes summarizer',
      ].join('\n'),
    },
  },
  {
    id: 'real_estate',
    title: 'Real Estate',
    title_zh: 'Real Estate',
    description: 'Listings, investing, and property operations.',
    reddit: {
      subreddits: [
        'realestate',
        'realestateinvesting',
        'realtors',
        'landlord',
        'propertymanagement',
        'mortgages',
        'firsttimehomebuyer',
        'homeowners',
        'househunting',
        'realestatelaw',
        'airbnbhosts',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'deal analyzer / roi calculator',
        'tenant screening workflow',
        'maintenance request tracking',
        'listing management',
        'rent collection reminders',
        'mortgage comparison tool',
      ].join('\n'),
    },
  },
  {
    id: 'health',
    title: 'Health',
    title_zh: 'Health',
    description: 'Patient journeys, care coordination, and wellness.',
    reddit: {
      subreddits: [
        'health',
        'healthcare',
        'medicine',
        'askdocs',
        'medical',
        'chronicillness',
        'diabetes',
        'autoimmune',
        'publichealth',
        'healthinsurance',
        'pharmacy',
        'wellness',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'appointment reminders',
        'symptom tracking',
        'medication schedule',
        'insurance claim tracker',
        'wellness habit tracking',
        'care coordination notes',
      ].join('\n'),
    },
  },
  {
    id: 'cooking',
    title: 'Cooking',
    title_zh: 'Cooking',
    description: 'Meals, grocery planning, and kitchen workflows.',
    reddit: {
      subreddits: [
        'cooking',
        'eatcheapandhealthy',
        'mealprep',
        'recipes',
        'slowcooking',
        'baking',
        'bbq',
        'food',
        'instantpot',
        'castiron',
        'vegetarian',
        'mealprepsunday',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'meal planning board',
        'pantry inventory',
        'recipe scaling calculator',
        'grocery list automation',
        'nutrition macro tracker',
        'leftover reuse ideas',
      ].join('\n'),
    },
  },
  {
    id: 'mental_health',
    title: 'Mental Health',
    title_zh: 'Mental Health',
    description: 'Mindfulness, therapy, and stress support.',
    reddit: {
      subreddits: [
        'mentalhealth',
        'anxiety',
        'depression',
        'adhd',
        'therapy',
        'ptsd',
        'stress',
        'bipolar',
        'selfhelp',
        'counseling',
        'mindfulness',
        'burnout',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'mood tracking journal',
        'therapy notes organization',
        'meditation habit tracker',
        'burnout recovery plan',
        'stress trigger log',
        'support resources directory',
      ].join('\n'),
    },
  },
  {
    id: 'design',
    title: 'Design',
    title_zh: 'Design',
    description: 'UX workflows, design systems, and collaboration.',
    reddit: {
      subreddits: [
        'design',
        'uxdesign',
        'userexperience',
        'graphic_design',
        'branding',
        'typography',
        'web_design',
        'ui_design',
        'productdesign',
        'figma',
        'designcritiques',
        'designsystems',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'design brief builder',
        'feedback collection',
        'asset library management',
        'design system checklist',
        'handoff to dev workflow',
        'accessibility review tool',
      ].join('\n'),
    },
  },
  {
    id: 'devtools',
    title: 'DevTools',
    title_zh: 'DevTools',
    description: 'Developer workflows, tooling, and infrastructure.',
    reddit: {
      subreddits: [
        'devtools',
        'programming',
        'webdev',
        'javascript',
        'typescript',
        'reactjs',
        'devops',
        'sysadmin',
        'cloud',
        'aws',
        'kubernetes',
        'docker',
        'vscode',
        'github',
        'softwareengineering',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'local dev environment setup',
        'ci pipeline debugging',
        'error log triage',
        'release checklist',
        'api testing harness',
        'code review workflow',
      ].join('\n'),
    },
  },
];
