export type StrategyTrack = {
  id: string;
  title: string;
  title_zh: string;
  description?: string;
  reddit: {
    subreddits: string[];
    keywordsText: string;
  };
};

const CORE_KEYWORDS = [
  'How do you... / What tool do you use for...',
  'Is there a tool that... / I wish there was...',
  'X software is terrible / alternative to X',
  "I'm spending hours doing...",
  'We keep messing up...',
];

export const STRATEGY_TRACKS: StrategyTrack[] = [
  {
    id: 'personal_finance',
    title: 'Personal Finance',
    title_zh: '理财',
    description: 'Budgeting, investing, and money management pain points.',
    reddit: {
      subreddits: [
        'personalfinance',
        'financialindependence',
        'frugal',
        'povertyfinance',
        'investing',
        'stocks',
        'bogleheads',
        'creditcards',
        'debtfree',
        'budgeting',
        'financialplanning',
        'retirement',
        'tax',
        'sidehustle',
        'money',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'budgeting app / expense tracking',
        'credit score monitoring',
        'debt payoff plan',
        'investment tracker',
        'tax filing software',
        'retirement planning tool',
      ].join('\n'),
    },
  },
  {
    id: 'fitness',
    title: 'Fitness',
    title_zh: '健身',
    description: 'Training, nutrition, and habit-building workflows.',
    reddit: {
      subreddits: [
        'fitness',
        'loseit',
        'bodyweightfitness',
        'gainit',
        'running',
        'weightlifting',
        'powerlifting',
        'crossfit',
        'xxfitness',
        'keto',
        'nutrition',
        'intermittentfasting',
        'yoga',
        'bodybuilding',
        'cycling',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'workout plan generator',
        'macro tracking / calorie logging',
        'meal prep planner',
        'habit tracker for training',
        'injury recovery routine',
        'sleep tracking for fitness',
      ].join('\n'),
    },
  },
  {
    id: 'pets',
    title: 'Pets',
    title_zh: '宠物',
    description: 'Pet care, training, and health management.',
    reddit: {
      subreddits: [
        'pets',
        'dogs',
        'cats',
        'puppy101',
        'dogtraining',
        'catcare',
        'petadvice',
        'veterinary',
        'dogfood',
        'catfood',
        'animaltraining',
        'rabbits',
        'parrots',
        'ferrets',
        'pethealth',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'vet appointment reminders',
        'pet insurance comparison',
        'behavior issues / training plan',
        'feeding schedule tracker',
        'grooming checklist',
        'lost pet recovery tool',
      ].join('\n'),
    },
  },
  {
    id: 'learning',
    title: 'Learning & Productivity',
    title_zh: '学习/效率',
    description: 'Study systems, focus, and knowledge management.',
    reddit: {
      subreddits: [
        'productivity',
        'getdisciplined',
        'studying',
        'learnprogramming',
        'languagelearning',
        'note-taking',
        'college',
        'gradschool',
        'selfimprovement',
        'learning',
        'digitalnomad',
        'notion',
        'obsidianmd',
        'anki',
        'reading',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'study planner / schedule',
        'spaced repetition workflow',
        'note-taking system',
        'focus timer / deep work',
        'course tracking dashboard',
        'reading list manager',
      ].join('\n'),
    },
  },
  {
    id: 'sales',
    title: 'Sales & CRM',
    title_zh: '销售/CRM',
    description: 'Pipeline, prospecting, and CRM operations.',
    reddit: {
      subreddits: [
        'sales',
        'salesops',
        'salesforce',
        'crm',
        'leadgeneration',
        'b2b',
        'coldemail',
        'marketing',
        'entrepreneur',
        'startups',
        'smallbusiness',
        'saas',
        'customersuccess',
        'growthhacking',
        'business',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'lead list building',
        'pipeline tracking',
        'deal follow-up reminders',
        'crm cleanup / data hygiene',
        'sales call notes',
        'outreach sequencing',
      ].join('\n'),
    },
  },
  {
    id: 'indie_saas',
    title: 'Indie SaaS',
    title_zh: 'SaaS/创业者',
    description: 'Founder workflows, product discovery, and growth.',
    reddit: {
      subreddits: [
        'saas',
        'startups',
        'entrepreneur',
        'indiehackers',
        'sideproject',
        'smallbusiness',
        'webdev',
        'programming',
        'productivity',
        'productmanagement',
        'marketing',
        'growthhacking',
        'nocode',
        'buildinpublic',
        'analytics',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'customer discovery / interviews',
        'onboarding checklist',
        'pricing experiments',
        'churn analysis',
        'support ticket workflow',
        'feature request tracking',
      ].join('\n'),
    },
  },
  {
    id: 'small_business_ops',
    title: 'Small Business Ops',
    title_zh: '小生意运营',
    description: 'Operations, bookkeeping, and day-to-day execution.',
    reddit: {
      subreddits: [
        'smallbusiness',
        'entrepreneur',
        'operations',
        'bookkeeping',
        'accounting',
        'ecommerce',
        'shopify',
        'etsy',
        'amazonfba',
        'marketing',
        'localbusiness',
        'logistics',
        'customerexperience',
        'projectmanagement',
        'retail',
      ],
      keywordsText: [
        ...CORE_KEYWORDS,
        'inventory tracking',
        'vendor management',
        'order fulfillment workflow',
        'cash flow tracker',
        'staff scheduling',
        'process checklist',
      ].join('\n'),
    },
  },
];
